### PR TITLE
Allow for a fixed inner height of the shell

### PR DESCRIPTION
**Pull request by rakr**
Using the prop shell-height it is now possible to have a fixed height.
If the content overflows, the inner shell scrolls smoothly to display
the latest line.

This PR fixes #1

### CODE REVIEW

**Comment by Lehoczky** [comment]
I really like this, especially with the smooth autoscroll behavior!

I think we could change one thing:

The terminal should have a scrollbar, because with this implementation the user can only see the previous lines by restarting the animation, and even then, I think it would be hard to copy a line for example.
I changed the overflow to `auto` for this and I understand why you choose `hidden` instead: the terminal shows a scrollbar even before it's content overflows.

image

We could make this work by changing the `style()` function inside the `TermynalLineMixin` to give a `display: none` when the terminal has a fixed height, but then the scrollTo function might break.

Another option is to emit a `new-line` event (the name is debatable) whenever we add a new line to the DOM, and let the developer, who uses this library implement the scrolling. This has the advantage of keeping the component more flexible, and maintainable.

```js
for (const line of this.lines) {
    await line.show()
    this.$emit("new-line", line.$el)
}
```

As a last thing, the scrollbar should be styled, because the native "design" looks terrible unfortunately:D

What do you think? Would you experiment with the implementation of this? If not, I can work on this myself so no worries.

**Comment by rakr** [comment]
I am on a Mac, so the scrollbar looks definitely better than on your screenshot.
I think that I like the idea of styling the scrollbar better.
An idea to enable your copy use case is to change the `overflow-y` to `scroll` at the end of the animation and to `hidden` at the start.

**Comment by Lehoczky** [comment]
I've created a new PR which makes the terminal window emit events, and I updated the playground to show an example which implements the scrolling effect as seen in this PR. Would you check that one out? #5 

I'd rather merge that implementation because it gives more flexibility to the user, and decouples the scrolling from the main library. Other devs might want to do something else with the new lines, or just simply implement a different scrolling effect.

**Comment by Lehoczky** [comment]
Closed, because this can be done after #5

**Pull request closed without merging**
